### ISSUE TITLE
How to handle "return" output parameter in birdy.client?

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/birdy#157]
## Description

The birdy client fails for ophidia-wps because one of the output parameters is the reserved keyword `return`. Shall we handle this in the birdy client?

We could update the sanitize method:
https://github.com/bird-house/birdy/blob/3f19a80f9a3c90797abb78185436fac4e04002e6/birdy/utils.py#L59

This is a question raised by @minomicetto when working with ophidia WPS:

> Actually, an argument of the operator `oph_list` is `return`… and all the operators have this argument… :-(
> See 
> https://ophidialab.cmcc.it/ophidia/wps/?request=DescribeProcess&service=WPS&version=1.0.0&identifier=all
> 
> I could change the name of this field to `return_code` (it is an error code in case the value is positive, 0 in case of success), but is it necessary?

## Environment

* Birdy version used, if any:
* Python version, if any:
* Operating System:

## Steps to Reproduce

```
>>> from birdy import WPSClient
>>> emu = WPSClient(url='https://ophidialab.cmcc.it/ophidia/wps')
>>> result = emu.oph_list(userid='cehbrecht',passwd=’NEXT MAIL',exec_mode='sync',cwd='/')
>>> result.get()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ophidia/oph-hub/birdy/birdy/client/outputs.py", line 32, in get
    return self._make_output(asobj)
  File "/home/ophidia/oph-hub/birdy/birdy/client/outputs.py", line 36, in _make_output
    self.processOutputs])
  File "/home/ophidia/.conda/envs/birdy/lib/python3.7/collections/__init__.py", line 364, in namedtuple
    raise ValueError('Type names and field names cannot be a '
ValueError: Type names and field names cannot be a keyword: 'return'
>>> 
```

**Comment by huard** [comment]
I think it is the client's job to adjust, so yes, birdy should work around this. We could add a trailing _ to all reserved words or something like that.

**Comment by cehbrecht** [comment]
@huard @minomicetto I make a PR for this.
