### ISSUE TITLE
handle encodings

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/birdy#2]
using demo wps service failed due to encoding error:

```
export WPS_SERVICE=http://geoprocessing.demo.52north.org:8080/52n-wps-webapp-3.3.1/WebProcessingService


$ birdy -h
Traceback (most recent call last):
 File "/home/pingu/.conda/envs/birdhouse/lib/python2.7/site-packages/birdhouse_birdy-0.1.0-py2.7.egg/birdy/__init__.py", line 149, in parse_wps_description wps.identification.abstract)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in position 2: ordinal not in range(128)
```

**Comment by cehbrecht** [comment]
just another encoding problem:

    $ export WPS_SERVICE=http://zoo.dev.publicamundi.eu/cgi-bin/zoo_loader.cgi
    $ birdy -h
    Traceback (most recent call last):
      File "/home/pingu/anaconda/lib/python2.7/site-packages/birdy/wpsparser.py", line 76, in parse_process_help
    help = help + str(process.abstract)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u03b8' in position 2114: ordinal not in range(128)

**Comment by cehbrecht** [comment]
Mentioned WPS services are offline. Encodings might be handled by the new Click CLI.

Close this ticket for now as duplicate of #10.
