### ISSUE TITLE
Update docs for native client

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/birdy#43]
## Description

Docs are currently in the Python module.

**Comment by huard** [comment]
Running pytest I have a regression

```
tests/test_native.py:9 (test_birdmod)
Traceback (most recent call last):
  File "/home/david/src/birdy/tests/test_native.py", line 13, in test_birdmod
    assert m.hello('david') == 'Hello david'
  File "/home/david/src/birdy/birdy/native.py", line 350, in wrapper
    out = self.execute(wrapped.__name__, **ba.arguments)
  File "/home/david/src/birdy/birdy/native.py", line 395, in execute
    out.append(self.process_output(o))
  File "/home/david/src/birdy/birdy/native.py", line 412, in process_output
    typ = BirdyCLI.get_param_type(out)
  File "/home/david/src/birdy/birdy/cli/base.py", line 90, in get_param_type
    if 'boolean' in param.dataType:
TypeError: argument of type 'NoneType' is not iterable
```
It seems output objects have no dataType attribute. Ideas ?
